config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', sessions:  'sessions' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_up' => 'devise/registration#new'
    get '/users/edit' => 'devise/registration#edit'
  end
  resources :pool, only: [:index] do
    collection do
      get 'api'
    end
  end
  resources :user, only: [:index] do
    member do
      post 'horse_race_object_click'
      post 'disable_by_admin'
      post 'enable_by_admin'
      post 'continue_membership_by_admin'
      post 'clear_membership_by_admin'
      post 'process_payment'
    end
    collection do
      post 'hook'
      post 'free_subscription_plan'
    end
  end
  resources :race_condition_details
  resources :rail_detail_ranks
  resources :score_report, only: [:index]
  resources :tips_report, only: [:index]
  resources :bets_report, only: [:index,:show] do
    collection do
      get 'graph'
      get 'api'
      get 'category'
      get 'by_week'
      get 'by_week_special'
    end
  end
  resources :class_report, only: [:index]
  resources :class_sectional, only: [:index]
  resources :outlier, only: [:index]
  resources :scorecard, only: [:index,:show] do
    collection do
      get :date
      get :total
      get :graph
      get :api
    end
  end
  resources :summary, only: [:show]
  resources :race_classes
  resources :race, only: [:show] do
    collection do
      get :cup
    end
  end
  resources :horse, only: [:show]
  resources :jockey, only: [:show]
  resources :trainer, only: [:show]
  resources :date, only: [:show,:index]
  resources :score_way, only: [:index]
  resources :posts
  resources :post_comments
  get '/all-posts', to: 'post_comments#index'
  resources :magic_ball, only: [:index,:show] do
    collection do
      get :api
      get :tool
    end
  end
  resources :forecast, only: [:index] do
    collection do
      get :ajax
    end
  end
  #resources :home, only: [:index]
  resources :gorilla_bets, only: [:index] do
    collection do
      get :by_week_special
    end
  end
  resources :upcoming_feature_races, only: [:index]
  resources :login, only: [:index]
  resources :main, only: [:index]
  resources :facebook, only: [:index]
  resources :public_info, only: [] do
    collection do
      get :'privacy_policy'
      get :'terms_and_conditions'
      get :'dutch_betting'
      get :'welcome_page'
    end
  end

  get 'dailytips', controller: :daily_tips, action: :index
  resources :daily_tips, only: [] do
    collection do
      get :races
      get :tracks
      get :tips
    end
  end

  resources :plans do
    resources :subscriptions do
      member do
        get :cancel_subscription
      end
      collection do
        get :free_trial
      end
    end
  end
  post :store_billing_detail, to: 'subscriptions#store_billing_detail'

  mount StripeEvent::Engine, at: '/stripe_events'
  root to: 'daily_tips#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'

  def index
    @plans = Plan.active
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%header.header
  .container
    .logo
      = link_to (image_tag "logo.png"), root_path
    %nav.navbar.navbar-expand-lg
      %a.navbar-brand{href: "#"} Navbar
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", type: "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.active
            = link_to 'Home', root_path
          %li.active
            = link_to 'About', welcome_page_public_info_index_path
          %li.active
            %a{href: "#plans"} Plans
          %li.active
            %a{href: "#plans"} Magic Eight ball
        %ul.navbar-nav.ml-auto
          -if user_signed_in?
            %li.active
              %a{href:edit_user_registration_path} Profile
            %li.active
              %a{href:destroy_user_session_path,method: :delete} Logout
          -else
            %li.active
              %a{"data-target" => "#SignInModal", "data-toggle" => "modal", href: "#"} Sign in
            %li.active
              %a{"data-target" => "#SignUpModal", "data-toggle" => "modal", href: "#"} Sign up
%section.caroseul
  .owl-carousel.owl-theme
    .item
      %span= image_tag "caroseul-1.jpg", alt: "Icon"
      .container
        .caroseul-caption
          %small Welcome to
          %h2 BetBuilder
          %a{href: "#plans"}
            View Plans
            %i.fa.fa-angle-double-right
    .item
      %span= image_tag "caroseul-1.jpg", alt: "Icon"
      .container
        .caroseul-caption
          %small Welcome to
          %h2 BetBuilder
          %a{href: "#plans"}
            View Plans
            %i.fa.fa-angle-double-right
%section.signup-for-free
  .container
    %h2
      %big We dig the stats, we’ve done the form,
      %small you get the tips- free, every day”
    -if !user_signed_in?
      %a{href: "#", "data-target" => "#SignUpModal", "data-toggle" => "modal"} Sign up for free tips daily
%section.description-wrap
  .container
    .d-flex
      .description-img.my-auto
        = image_tag "img-01.png", alt: "Icon", class: "for-desktop"
        = image_tag "img-02.jpg", alt: "Icon", class: "for-mobile-ipade"
      .description-text
        %p
          At Betbuilder we have devisived a way of teaching a computer how to do the form without the use of price and market sentiment.
          %strong What does this mean?
        %p
          You get an objective tipping service, an effecitve tipping service and a service that isn’t concerned with price- just winners.
          %strong But guess what?
          It’s gets even better than that, we present these picks for every race meeting, everyday, for free! Yep. Every top 4 race selection, free.
        %p
          The difference between us and the competition is we measure everything. Current daily tips are resulted live after they settle, we measure the success rate of our picks and we also measure which race track we are successful at so we can get better.
        %p
          So the final product is smart, scientific tipping for free, everyday, to balance your own form analysis with confidence.  DELETE NEXT PART TO MONEY BAG AFTER GORILLAS have devised a method for each betting type which is actually profitable, found in our Gorillas membership appropriately named because you get exactly that –
          %strong Gorillas!!
          In addition to this we have jam packed our Pineapples subscription with tools not found anywhere else: Race strength, Best betting markets, Magic eightball that provides tips at click for next to go races, exotics numbers and more.
        %p
          %strong The features don’t end at tipping
          and we are just getting started. So don’t listen to some smart alec bookmaker has been OR some desperate punter looking for the next way to waste his money, think objectively, be patient and the spoils will be yours. Hope to see you track-side punters.
        %h6
          %em Regards,
          %strong Paul Gradwell
          %em Betbuilder founder and statistics enthusiast
%section.plans-wrap#plans
  .container
    %h2
      %big Plans
    %ul.d-flex.plans-ul
      - @plans.each do |plan|
        %li
          .plans-box{class: %w[pineapples_tier_1 magic_eightball_tier_3].include?(plan.payment_gateway_plan_identifier) ? '' : 'coming_soon'}
            %h3
              = plan.name
            %h6
              %strong
                = "#{humanized_money_with_symbol(plan.price)} /"
              = "#{plan.interval} #{plan.interval_count}"
            .plans-point
              = plan.description.html_safe
            - subscription = current_user.get_subscription(plan.id) if current_user
            .icon-img= image_tag "home_#{plan.payment_gateway_plan_identifier}.png", height: 90, alt: "Icon"
            .subscribe-btn
              -if %w[pineapples_tier_1 magic_eightball_tier_3].include?(plan.payment_gateway_plan_identifier)
                - if user_signed_in?
                  - if subscription
                    = link_to("Subscribed", plan_subscription_path(plan, subscription), class:'btn btn-info')
                  - else
                    %a{"data-target" => "#addressModal", "data-toggle" => "modal", :type => "link", onclick: "$('.plan_id').val(#{plan.id})"} Subscribe
                -else
                  %a{href: "#", "data-target" => "#SignInModal", "data-toggle" => "modal"} Subscribe
              - else
                %a{:disabled => "disabled", :type => "link"} Subscribe
%footer.footer
  .container
    %p 18+ Don't let the game play you. Stay in control. Gamble responsibly. Think! About your choices.
    %p
      Call Gambling Help on
      %strong 1800 858 858
      or visit
      %em www.gamblinghelp.nsw.gov.au
      or
      %em www.gamblinghelponline.org.au
= render 'plans/address_modal' if user_signed_in?
#SignUpModal.modal.fade{role: "dialog"}
  .modal-dialog
    .modal-content
      .modal-body
        .card
          .card-body
            %h1{style: "text-align:center;"} Sign up
            %a{href: "/users/auth/facebook"}
              %img{src: "#{image_path('fb_login.png')}", style: "width:100%;padding:20px;"}/
            %h3{style: "text-align:center;"} Or
            = render 'devise/registrations/form'
#SignInModal.modal.fade{role: "dialog"}
  .modal-dialog
    .modal-content
      .modal-body
        .card
          .card-body
            %a{href: "/users/auth/facebook"}
              %img{src: "#{image_path('fb_login.png')}", style: "width:100%;padding:20px;"}/
            %h1.card-title{style: "text-align:center;"} OR
            %h3{style: "text-align:center;"} Sign in with an account
            %p#login_error.hide Invalid Email or password
            = form_for(resource, as: resource_name, url: session_path(resource_name), remote: true, authenticity_token: true, html: { id: 'login_form' }) do |f|
              .form-group
                .field
                  = f.email_field :email, autofocus: true, placeholder: 'Email address', class: 'form-control', id: 'email'
              .form-group
                .field
                  = f.password_field :password, autocomplete: 'off', placeholder: 'Password', class: 'form-control', id: 'password'
              %p
                By entering Betbuilder I accept
                %a{href: terms_and_conditions_public_info_index_path, target: "_blank"} Terms and Conditions
              .actions
                = f.submit 'Sign in', class: 'btn btn-secondary', style: 'width: 100%; font-size: 22px; font-weight: bold;'
:javascript
  $('.owl-carousel').owlCarousel({
    items:1,
    margin:0,
    animateIn: 'fadeIn',
    animateOut: 'fadeOut'
  });
  $(document).ready(function($) {
    $('a[href^="#"]').bind('click.smoothscroll',function (e) {
      e.preventDefault();
      var target = this.hash,
          $target = $(target);
      $('html, body').stop().animate( {
        'scrollTop': $target.offset().top-40
      }, 900, 'swing', function () {
        window.location.hash = target;
      });
    });
  });

app/views/home/index_old.html.erb
<header class="header">
  <div class="container">
    <div class="logo"><a href=""><%= image_tag "logo.png", alt: "Logo" %></a></div>
    <nav class="navbar navbar-expand-lg">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="active"><a href="#">Home</a></li>
          <li class="active"><a href="#">About</a></li>
          <li class="active"><a href="#">Plans</a></li>
          <li class="active"><a href="#">Magic Eight ball</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="active"><a href="#" data-toggle="modal" data-target="#SignInModal">Sign in</a></li>
          <li class="active"><a href="#" data-toggle="modal" data-target="#SignUpModal">Sign up </a></li>
        </ul>
      </div>
    </nav>
  </div>
</header>

<section class="caroseul">
  <div class="owl-carousel owl-theme">
    <div class="item">
      <span><%= image_tag "caroseul-1.jpg", alt: "Icon" %></span>
      <div class="container">
        <div class="caroseul-caption">
          <small>Welcome to</small>
          <h2>BetBuilder</h2>
          <p>When an unknown printer took a galley of type and  <br/> scrambled it to make a type book.</p>
          <a href="">View Plans <i class="fa fa-angle-double-right "></i></a>
        </div>
      </div>
    </div>
    <div class="item">
      <span><%= image_tag "caroseul-1.jpg", alt: "Icon" %></span>
      <div class="container">
        <div class="caroseul-caption">
          <small>Welcome to</small>
          <h2>BetBuilder</h2>
          <p>When an unknown printer took a galley of type and  <br/> scrambled it to make a type book.</p>
          <a href="">View Plans <i class="fa fa-angle-double-right "></i></a>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="signup-for-free">
  <div class="container">
    <h2>
      <big>We dig the stats, we’ve done the form, </big>
      <small>you get the tips- free, every day”</small>
    </h2>
    <a href="">Sign up for free tips daily</a>
  </div>
</section>

<section class="description-wrap">
  <div class="container">
    <div class="d-flex">
      <div class="description-img">
        <%= image_tag "img-01.png", alt: "Icon" %>
      </div>
      <div class="description-text">
        <p>At Betbuilder we have devisived a way of teaching a computer how to do the form without the use of price and market sentiment. <strong>What does this mean?</strong></p>
        <p>You get an objective tipping service, an effecitve tipping service and a service that isn’t concerned with price- just winners. <strong>But guess what?</strong> It’s gets even better than that, we present these picks for every race meeting, everyday, for free! Yep. Every top 4 race selection, free.</p>
        <p>The difference between us and the competition, we measure everything. Current day tips are results live as they settle, the average price of our succesful picks, the success rate of our picks, which race track we are successful at and more! Everything. You get smart, scientific tipping for free, everyday, to balance your own form analysis with confidence. However we haven’t stopped there. We have devised a method for each betting type which is actually profitable, found in our Gorillas memerbship appropirately named because you get exactly that – <strong>Gorillas (insert cash symbol)!!</strong> In addition to this we have jam packed our Pineapples subscription with tools not found anywhere else: Race strength, Best betting markets, Magic eightball that provides tips at click for next to go races, exotics numbers and more. </p>
        <p><strong>The features don’t end at tipping</strong> and we are just getting started. So don’t listen to some smart alec bookmaker has been OR some desperate punter looking for the next way to waste his money, think objectivelyt, be patient and the spoils will be yours. Hope to see you trackside punters.</p>
        <h6>
          <em>Regards,</em>
          <strong>Paul Gradwell</strong>
          <em>Betbuilder founder and statistics enthusiast</em>
        </h6>
      </div>
    </div>
  </div>
</section>

<section class="plans-wrap">
  <div class="container">
    <h2>
      <big>Plans</big>
      <em>Into electronic typesetting.</em>
    </h2>
    <ul class="d-flex plans-ul">
      <li>
        <div class="plans-box">
          <h3>Pineapples</h3>
          <h6><strong>$8.88/</strong> Week billed Monthly</h6>
          <ul class="plans-point">
            <li>Daily tips Pushed to your account</li>
            <li>First four numbers</li>
            <li>Quaddie numbers</li>
            <li>Magic eight bal</li>
            <li>Best betting markets (races)</li>
            <li>Bets strength per race</li>
          </ul>
          <div class="icon-img"><%= image_tag "icon-1.jpg", alt: "Icon" %></div>
          <div class="subscribe-btn"><a href="">Subscribe</a></div>
        </div>
      </li>
      <li>
        <div class="plans-box">
          <h3>Gorillas</h3>
          <h6><Strong>$18.88/</strong> Week billed Monthly</h6>
          <ul class="plans-point">
            <li>All the Pineapples membership benefits</li>
            <li>Proven winning bet strategies tailored to your bank and betting days</li>
            <li>Black book access (ours + your)</li>
          </ul>
          <div class="icon-img"><%= image_tag "icon-2.jpg", alt: "Icon" %></div>
          <div class="subscribe-btn"><a href="">Subscribe</a></div>
        </div>
      </li>
      <li>
        <div class="plans-box">
          <h3>Magic Eightball</h3>
          <h6><strong>$10 for 3days</strong> <small>(1 day + 2 days free)</small></h6>
          <ul class="plans-point">
            <li>Tips provided based on proprietarty algorithms dilvered in the click of a button. You can’t do the form, let the eightball pick the winners for you! (also included in memberships)</li>
          </ul>
          <div class="icon-img"><%= image_tag "icon-3.jpg", alt: "Icon" %></div>
          <div class="subscribe-btn"><a href="">Subscribe</a></div>
        </div>
      </li>
    </ul>
  </div>
</section>

<footer class="footer">
  <div class="container">
    <p>18+ Don't let the game play you. Stay in control. Gamble responsibly. Think! About your choices.</p>
    <p>Call Gambling Help on <strong>1800 858 858</strong> or visit <em>www.gamblinghelp.nsw.gov.au</em> or <em>www.gamblinghelponline.org.au</em></p>
  </div>
</footer>

<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->

<div id="SignUpModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="card">
          <div class="card-body">
            <h1 style="text-align:center;">Sign up</h1>
            <a href="/users/auth/facebook">
              <img src="<%= image_path('fb_login.png') %>" style="width:100%;padding:20px;"/>
            </a>
            <h3 style="text-align:center;">Or</h3>
            <%= render 'devise/registrations/form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="SignInModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div class="card">
          <div class="card-body">
            <a href="/users/auth/facebook">
              <img src="<%= image_path('fb_login.png') %>" style="width:100%;padding:20px;"/>
            </a>
            <h1 class="card-title" style="text-align:center;">OR</h1>
            <h3 style="text-align:center;">Sign in with an account</h3>
            <p id="login_error" class="hide">Invalid Email or password</p>
            <%= form_for(resource, as: resource_name, url: session_path(resource_name), remote: true, authenticity_token: true, html: { id: 'login_form' }) do |f| %>
            <div class="form-group">
              <div class="field">
                <%= f.email_field :email, autofocus: true, placeholder: 'Email address', class: 'form-control', id: 'email' %>
              </div>
            </div>
            <div class="form-group">
              <div class="field">
                <%= f.password_field :password, autocomplete: 'off', placeholder: 'Password', class: 'form-control', id: 'password' %>
              </div>
            </div>
            <p>
              By entering Betbuilder I accept
              <a href="<%= terms_and_conditions_public_info_index_path %>" target="_blank">Terms and Conditions</a>
            </p>
            <div class="actions">
              <%= f.submit 'Sign in', class: 'btn btn-secondary', style: 'width: 100%; font-size: 22px; font-weight: bold;' %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $('.owl-carousel').owlCarousel({
    items:1,
    margin:0,
    animateIn: 'fadeIn',
    animateOut: 'fadeOut'
  });
</script>