config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', sessions:  'sessions' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_up' => 'devise/registration#new'
    get '/users/edit' => 'devise/registration#edit'
  end
  resources :pool, only: [:index] do
    collection do
      get 'api'
    end
  end
  resources :user, only: [:index] do
    member do
      post 'horse_race_object_click'
      post 'disable_by_admin'
      post 'enable_by_admin'
      post 'continue_membership_by_admin'
      post 'clear_membership_by_admin'
      post 'process_payment'
    end
    collection do
      post 'hook'
      post 'free_subscription_plan'
    end
  end
  resources :race_condition_details
  resources :rail_detail_ranks
  resources :score_report, only: [:index]
  resources :tips_report, only: [:index]
  resources :bets_report, only: [:index,:show] do
    collection do
      get 'graph'
      get 'api'
      get 'category'
      get 'by_week'
      get 'by_week_special'
    end
  end
  resources :class_report, only: [:index]
  resources :class_sectional, only: [:index]
  resources :outlier, only: [:index]
  resources :scorecard, only: [:index,:show] do
    collection do
      get :date
      get :total
      get :graph
      get :api
    end
  end
  resources :summary, only: [:show]
  resources :race_classes
  resources :race, only: [:show] do
    collection do
      get :cup
    end
  end
  resources :horse, only: [:show]
  resources :jockey, only: [:show]
  resources :trainer, only: [:show]
  resources :date, only: [:show,:index]
  resources :score_way, only: [:index]
  resources :posts
  resources :post_comments
  get '/all-posts', to: 'post_comments#index'
  resources :magic_ball, only: [:index,:show] do
    collection do
      get :api
      get :tool
    end
  end
  resources :forecast, only: [:index] do
    collection do
      get :ajax
    end
  end
  #resources :home, only: [:index]
  resources :gorilla_bets, only: [:index] do
    collection do
      get :by_week_special
    end
  end
  resources :upcoming_feature_races, only: [:index]
  resources :login, only: [:index]
  resources :main, only: [:index]
  resources :facebook, only: [:index]
  resources :public_info, only: [] do
    collection do
      get :'privacy_policy'
      get :'terms_and_conditions'
      get :'dutch_betting'
      get :'welcome_page'
    end
  end

  get 'dailytips', controller: :daily_tips, action: :index
  resources :daily_tips, only: [] do
    collection do
      get :races
      get :tracks
      get :tips
    end
  end

  resources :plans do
    resources :subscriptions do
      member do
        get :cancel_subscription
      end
      collection do
        get :free_trial
      end
    end
  end
  post :store_billing_detail, to: 'subscriptions#store_billing_detail'

  mount StripeEvent::Engine, at: '/stripe_events'
  root to: 'daily_tips#index'
end

app/models/rail_detail_rank.rb
class RailDetailRank < ApplicationRecord
  def self.get_external
    sql = "select distinct rail from races where rail not in (select title from rail_detail_ranks) and coalesce(rail,'')<>''"
    ActiveRecord::Base.connection.execute(sql).values.map{|v| v[0]}
  end
end

app/controllers/rail_detail_ranks_controller.rb
class RailDetailRanksController < ApplicationController
  before_action :access_deny_in_if_not_an_admin
  before_action :set_rail_detail_rank, only: [:show, :edit, :update, :destroy]

  # GET /rail_detail_ranks
  def index
    @rail_detail_ranks = RailDetailRank.all
  end

  # GET /rail_detail_ranks/1
  def show
  end

  # GET /rail_detail_ranks/new
  def new
    @rail_detail_rank = RailDetailRank.new
  end

  # GET /rail_detail_ranks/1/edit
  def edit
  end

  # POST /rail_detail_ranks
  def create
    @rail_detail_rank = RailDetailRank.new(rail_detail_rank_params)

    if @rail_detail_rank.save
      redirect_to @rail_detail_rank, notice: 'Rail detail rank was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /rail_detail_ranks/1
  def update
    if @rail_detail_rank.update(rail_detail_rank_params)
      redirect_to @rail_detail_rank, notice: 'Rail detail rank was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /rail_detail_ranks/1
  def destroy
    @rail_detail_rank.destroy
    redirect_to rail_detail_ranks_url, notice: 'Rail detail rank was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rail_detail_rank
      @rail_detail_rank = RailDetailRank.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def rail_detail_rank_params
      params.require(:rail_detail_rank).permit(:title, :rank)
    end
end

app/helpers/rail_detail_ranks_helper.rb
module RailDetailRanksHelper
end

app/views/rail_detail_ranks/_form.html.haml
= form_for @rail_detail_rank do |f|
  - if @rail_detail_rank.errors.any?
    #error_explanation
      %h2= "#{pluralize(@rail_detail_rank.errors.count, "error")} prohibited this rail_detail_rank from being saved:"
      %ul
        - @rail_detail_rank.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :rank
    = f.number_field :rank
  .actions
    = f.submit 'Save'

app/views/rail_detail_ranks/edit.html.haml
%h1 Editing rail_detail_rank

= render 'form'

= link_to 'Show', @rail_detail_rank
\|
= link_to 'Back', rail_detail_ranks_path

app/views/rail_detail_ranks/index.html.haml
%h1 Listing rail_detail_ranks
-external = RailDetailRank.get_external.join(', ')
-unless external.blank?
  %h3 External rail info (out of our list)
  %p=external
%table
  %thead
    %tr
      %th Title
      %th Rank
      %th
      %th
      %th

  %tbody
    - @rail_detail_ranks.order(:rank).each do |rail_detail_rank|
      %tr
        %td= rail_detail_rank.title
        %td= rail_detail_rank.rank
        %td= link_to 'Show', rail_detail_rank
        %td= link_to 'Edit', edit_rail_detail_rank_path(rail_detail_rank)
        %td= link_to 'Destroy', rail_detail_rank, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Rail detail rank', new_rail_detail_rank_path

app/views/rail_detail_ranks/new.html.haml
%h1 New rail_detail_rank

= render 'form'

= link_to 'Back', rail_detail_ranks_path

app/views/rail_detail_ranks/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @rail_detail_rank.title
%p
  %b Rank:
  = @rail_detail_rank.rank

= link_to 'Edit', edit_rail_detail_rank_path(@rail_detail_rank)
\|
= link_to 'Back', rail_detail_ranks_path