config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', sessions:  'sessions' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/sign_up' => 'devise/registration#new'
    get '/users/edit' => 'devise/registration#edit'
  end
  resources :pool, only: [:index] do
    collection do
      get 'api'
    end
  end
  resources :user, only: [:index] do
    member do
      post 'horse_race_object_click'
      post 'disable_by_admin'
      post 'enable_by_admin'
      post 'continue_membership_by_admin'
      post 'clear_membership_by_admin'
      post 'process_payment'
    end
    collection do
      post 'hook'
      post 'free_subscription_plan'
    end
  end
  resources :race_condition_details
  resources :rail_detail_ranks
  resources :score_report, only: [:index]
  resources :tips_report, only: [:index]
  resources :bets_report, only: [:index,:show] do
    collection do
      get 'graph'
      get 'api'
      get 'category'
      get 'by_week'
      get 'by_week_special'
    end
  end
  resources :class_report, only: [:index]
  resources :class_sectional, only: [:index]
  resources :outlier, only: [:index]
  resources :scorecard, only: [:index,:show] do
    collection do
      get :date
      get :total
      get :graph
      get :api
    end
  end
  resources :summary, only: [:show]
  resources :race_classes
  resources :race, only: [:show] do
    collection do
      get :cup
    end
  end
  resources :horse, only: [:show]
  resources :jockey, only: [:show]
  resources :trainer, only: [:show]
  resources :date, only: [:show,:index]
  resources :score_way, only: [:index]
  resources :posts
  resources :post_comments
  get '/all-posts', to: 'post_comments#index'
  resources :magic_ball, only: [:index,:show] do
    collection do
      get :api
      get :tool
    end
  end
  resources :forecast, only: [:index] do
    collection do
      get :ajax
    end
  end
  #resources :home, only: [:index]
  resources :gorilla_bets, only: [:index] do
    collection do
      get :by_week_special
    end
  end
  resources :upcoming_feature_races, only: [:index]
  resources :login, only: [:index]
  resources :main, only: [:index]
  resources :facebook, only: [:index]
  resources :public_info, only: [] do
    collection do
      get :'privacy_policy'
      get :'terms_and_conditions'
      get :'dutch_betting'
      get :'welcome_page'
    end
  end

  get 'dailytips', controller: :daily_tips, action: :index
  resources :daily_tips, only: [] do
    collection do
      get :races
      get :tracks
      get :tips
    end
  end

  resources :plans do
    resources :subscriptions do
      member do
        get :cancel_subscription
      end
      collection do
        get :free_trial
      end
    end
  end
  post :store_billing_detail, to: 'subscriptions#store_billing_detail'

  mount StripeEvent::Engine, at: '/stripe_events'
  root to: 'daily_tips#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :bookmakers
  has_many :post_comments
  has_many :user_payments
  has_many :subscriptions
  has_many :plans, :through => :subscriptions
  has_one :billing_address, class_name: BillingAddress, :dependent => :destroy
  has_one :delivery_address, class_name: DeliveryAddress, :dependent => :destroy

  require 'unirest'
  STATES = ['Non-AUS','QLD','NT','ACT','VIC','WA','TAS','NSW']

  validates :first_name, length: { minimum: 3 }, on: :update
  validates :last_name, length: { minimum: 3 }, on: :update
  validates :state_manual, inclusion: User::STATES, on: :update

  # Include default devise modules. Others available are:
  #:recoverable, :rememberable, :registerable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable, :omniauthable, :registerable, :timeoutable, omniauth_providers: [:facebook]

  MINT = 'Mint'
  PINEAPPLE = 'Pineapple'

  def is_admin?
    is_admin
  end

  def show_membership
    if disabled_by_admin
      'Disabled by admin'
    elsif enabled_by_admin
      'Infinity by admin'
    elsif !membership_up.blank? && membership_up>Time.now
      "#{MINT} up #{membership_up.strftime('%d/%m/%Y')}"
    else
      'You are currently a free service member'
    end
  end

  def full_name
    first_name.to_s + " " + last_name.to_s
  end

  def has_first_tier?
    plans.where(payment_gateway_plan_identifier: 'pineapples_tier_1').count > 0
  end

  def has_second_tier?
    plans.where(payment_gateway_plan_identifier: 'gorillas_tier_2').count > 0
  end

  def has_third_tier?
    plans.where(payment_gateway_plan_identifier: 'magic_eightball_tier_3').each{|p| get_subscription(p.id)}
    return plans.where(payment_gateway_plan_identifier: 'magic_eightball_tier_3').count > 0
  end

  def get_subscription(plan_id)
    subscription = subscriptions.where(plan_id: plan_id).first
    if subscription.present?
      if subscription.payment_gateway_subscription_id == 'Free Trial'
        if Date.today > Date.parse("25/01/2019")
          SubscriptionHistory.create(user: self, plan_id: plan_id, subscribed_by: self.id, status: :canceled, payment_gateway_subscription_id: 'Free Trial', message: 'cancel subscription by user with stripe')
          subscription.destroy
          return nil
        else
          return subscription
        end
      else
        lookup_subscription = Stripe::Subscription.retrieve(subscription.payment_gateway_subscription_id)
        if lookup_subscription.status == "active"
          return subscription
        else
          SubscriptionHistory.create(user: self, plan_id: plan_id, subscribed_by: self.id, status: :canceled, payment_gateway_subscription_id: subscription.payment_gateway_subscription_id, message: 'cancel subscription by user with stripe')
          subscription.destroy
          return nil
        end
      end
    else
      return nil
    end
  end

  def continue_membership
    self.membership_up = ((membership_up.blank? || membership_up < Time.now) ? Time.now : membership_up) + 86400*7
    self.save
  end

  def clear_membership
    self.membership_up = nil
    self.save
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.process_ip_address(ip)
    result = {aus: false, nsw: false}
    begin
      link = "https://api.ipstack.com/#{ip}?access_key=c6d3ce93c07d4888f0c2c45456d0a7b5"
      request = Unirest.get(link)
      data = request.body
      if data.include?('country_name') && data['country_name']=='Australia'
        result[:aus] = true
      end
      if data.include?('region_code') && data['region_code']=='NSW'
        result[:nsw] = true
      end
      if data.include?('region_code') && %w[QLD NT ACT VIC WA TAS NSW].include?(data['region_code'])
        result[:state] = data['region_code']
      end
    rescue
      Rails.logger.error("IP stack error in #{ip}")
    end
    result
  end

  def process_ip_address
    unless current_sign_in_ip==ip_processed
      result = User.process_ip_address(current_sign_in_ip)
      self.is_aus = result[:aus]
      self.is_nsw = result[:nsw]
      self.state = result[:state]
      self.ip_processed = current_sign_in_ip
      self.save
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  require 'paypal_lib'

  protect_from_forgery except: [:hook]
  before_action :access_deny_in_if_not_an_admin, except: [:hook,:process_payment]
  before_action :access_deny_in_if_not_a_user, only: [:process_payment]

  def index
    @users = User.includes(:bookmakers).where(terms_confirmed:true)
  end

  def horse_race_object_click
    @user = User.find(params[:id])
    if params[:special].to_i.zero?
      @user.banner_click_count += 1
    else
      @user.banner_click_count_special += 1
    end
    @user.save
    render plain: 'ok'
  end

  def disable_by_admin
    @user = User.find(params[:id])
    @user.disabled_by_admin = params[:reverse].to_i.zero?
    @user.save
    redirect_to(user_index_path) and return
  end

  def enable_by_admin
    @user = User.find(params[:id])
    @user.enabled_by_admin = params[:reverse].to_i.zero?
    @user.save
    redirect_to(user_index_path) and return
  end

  def continue_membership_by_admin
    @user = User.find(params[:id])
    @user.continue_membership
    redirect_to(user_index_path) and return
  end

  def clear_membership_by_admin
    @user = User.find(params[:id])
    @user.clear_membership
    redirect_to(user_index_path) and return
  end

  def process_payment
    @user = User.find(params[:id])
    @user_payment = UserPayment.create(user:@user)
    redirect_to @user_payment.paypal_url(edit_user_registration_path)
  end

  def hook
    params.permit!
    status = params[:payment_status]
    if status == 'Completed' && PayPalLib.verified?(params.to_hash)
      @user_payment = UserPayment.find(params[:invoice])
      @user_payment.update_attributes notification_params: params.to_hash, status: status, transaction_id: params[:txn_id], purchased_at: Time.now
    end
    render plain: 'ok'
  end

  def free_subscription_plan
    @user = User.find_by_email(params[:user_email])
    SubscriptionHistory.create(user: @user, plan_id: params[:plan_id], subscribed_by: current_user.id, status: :active, message: 'create subscription by admin')
    Subscription.create!(user: @user, plan_id: params[:plan_id], start_date: Time.zone.now.to_date, status: :active)
    redirect_to(user_index_path, notice: 'Plan subscription created successfully')
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/index.html.haml
.container.themed-content
  .row
    .col-lg-12
      %h1 Terms confirmed users
      %table#historyMatches.table.table-bordered.table-responsive
        %thead
          %tr
            %th email
            %th created at
            %th last sign in at
            %th state
            %th first
            %th last
            %th manual
            %th bookmakers
            %th clicks
            -#%th Membership
            %th Subscription Plan
        %tbody
          -@users.each do |user|
            %tr
              %td=user.email
              %td{'data-sort': user.created_at.strftime('%Y/%m/%d')}=user.created_at.strftime('%d/%m/%Y')
              %td{'data-sort': user.last_sign_in_at.strftime('%Y/%m/%d')}=user.last_sign_in_at.strftime('%d/%m/%Y')
              %td=user.state
              %td=user.first_name
              %td=user.last_name
              %td=user.state_manual
              %td=user.bookmakers.map(&:title).join(',')
              %td="#{user.banner_click_count}/#{user.banner_click_count_special}"
              -if false
                %td
                  =user.show_membership
                  %br
                  -if user.disabled_by_admin
                    =link_to('Enable',disable_by_admin_user_path(user,reverse:1),method: :post)
                  -else
                    =link_to('Disable',disable_by_admin_user_path(user),method: :post)
                  %br
                  -if user.enabled_by_admin
                    =link_to('Usual access',enable_by_admin_user_path(user,reverse:1),method: :post)
                  -else
                    =link_to('Endless access',enable_by_admin_user_path(user),method: :post)
                  %br
                  =link_to('Continue access',continue_membership_by_admin_user_path(user),method: :post)
                  %br
                  =link_to('Clear',clear_membership_by_admin_user_path(user),method: :post,:data => {:confirm => 'Are you sure?'})
              %td
                = plan = user.subscriptions.map{|s| s.plan.name }.join(", ")
                = link_to "Subscription", '#SubscriptionModal', 'data-toggle' => 'modal', onclick: "$('#SubscriptionModal .modal-title span').html('#{user.email}');$('#user_email').val('#{user.email}')" if plan.blank?

#SubscriptionModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title
          Add Plan to
          %span
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      = form_tag free_subscription_plan_user_index_path do
        .modal-body
          %input#user_email{:name => "user_email", :type => "hidden"}/
          .form-group
            %label Select Plan
            = select_tag "plan_id", options_from_collection_for_select(Plan.all, "id", "name"), class: 'form-control'
        .modal-footer
          %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
          %button.btn.btn-primary{:type => "submit"} Add Subscription Plan